services:
  backend:
    build:
      context: ./backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    environment:
      - ENVIRONMENT=development

  frontend:
    build:
      context: ./frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    environment:
      - WATCHPACK_POLLING=true

    depends_on:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
